### ISSUE TITLE
Escaping HTML twice in image alt tag

### ISSUE THREAD

**Issue by cbreeden** [jgm/cheapskate#15]
While working on a solution for a [similar bug](https://github.com/markdown-it/markdown-it/issues/237) on markdown-it, it was brought to my attention that cheapskate may suffer from the same bug.  This was detecting using [Babelmark 2](http://johnmacfarlane.net/babelmark2/?text=!%5B%26%5D%28%23%29), which is currently using `cheapskate 0.1.0.1`; so I am not sure if this has been fixed since or not.

Given an input:

```
![&](#)
```

We obtain an output:

```
<p><img src="#" alt="&amp;amp;" /></p>
```

Expected output:

```
<p><img src="#" alt="&amp;" /></p>
```

**Comment by jgm** [comment]
I updated babelmark2 to use cheapskate 0.1.0.5 and the
problem disappeared.

+++ cbreeden [May 15 16 15:44 ]:
