### ISSUE TITLE
Compile failure w/ GHC 7.4

### ISSUE THREAD

**Issue by hvr** [jgm/cheapskate#22]
```
Configuring library for cheapskate-0.1.1..
Preprocessing library for cheapskate-0.1.1..
Building library for cheapskate-0.1.1..

Cheapskate/Types.hs:13:8:
    Could not find module `GHC.Generics'
    It is a member of the hidden package `ghc-prim'.
    Perhaps you need to add `ghc-prim' to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
cabal: Failed to build cheapskate-0.1.1 (which is required by exe:cheapskate from cheapskate-0.1.1).
```

I've already revised the meta-data for the affected release (see https://hackage.haskell.org/package/cheapskate-0.1.1/revisions/) to prevent the cabal solver from picking up cheapskate-0.1.1 with GHCs prior to GHC 7.6/base-4.6

**Comment by hvr** [comment]
@jgm ping? 

I've just had to make another revision for the latest release at https://hackage.haskell.org/package/cheapskate-0.1.1.1/revisions/

**Comment by jgm** [comment]
I'm fine with the revision. This is basically an
unmaintained package.  I make minimal changes occasionally.
I've pushed this change to the repository so it won't
be lost in the next release.

Herbert Valerio Riedel <notifications@github.com>
writes:
