### ISSUE TITLE
support for reference-style links

### ISSUE THREAD

**Issue by gbaz** [jgm/cheapskate#24]
http://spec.commonmark.org/0.28/#reference-link
http://spec.commonmark.org/0.28/#link-reference-definitions

As per: https://github.com/haskell/hackage-server/issues/650

**Comment by jgm** [comment]
This is basically an unsupported library and has been
for some time.  I don't plan to put any more work into
it. I'd recommend using cmark.

+++ gbaz [Jan 15 18 07:15 ]:

**Comment by jgm** [comment]
If you can tolerate a binding to a C library, I recommend
using cmark or cmark-gfm.

**Comment by gbaz** [comment]
Thanks for the pointer to cmark-gfm!
