### ISSUE TITLE
Build with ghc-8.6 containers

### ISSUE THREAD

**Issue by juhp** [jgm/cheapskate#29]
With Stackage Nightly:

containers-0.6.0.1 is out of bounds for:
- [ ] cheapskate-0.1.1 (>=0.4 && < 0.6). Sean Hunt <scshunt@csclub.uwaterloo.ca @scshunt. @jgm. Used by: library

**Comment by juhp** [comment]
Okay I see this is already fixed in #28 PR.
Is it possible to have a Hackage revision or (point release) for this?

**Comment by jgm** [comment]
I just published a point release.

**Comment by juhp** [comment]
Thanks :)
I don't see it in Hackage, or you want me to test it first?

**Comment by jgm** [comment]
Sorry - it's there now.

**Comment by juhp** [comment]
Thanks, pandoc should be in tomorrow's Stackage Nightly

**Comment by jgm** [comment]
Jens Petersen <notifications@github.com> writes:

> Thanks, pandoc should be in tomorrow's Stackage Nightly


Thanks for that!
